### PR TITLE
Add rule for wrapping @ attributes on function and type declarations

### PR DESCRIPTION
**Pull request by calda**
This PR adds a rule for wrapping @ attributes (like `@objc`, `@discardableResult`, and `@available`).

It includes separate configuration points for function declarations (`--funcattributes`) and type declarations (`--typeattributes`). Both options are marked as `preserve` by default, so this rule is 100% opt-in.

### Examples

`--funcattributes new-line`

```diff
- @objc func foo() {}
+ @objc
+ func foo() { }
```

`--funcattributes same-line`

```diff
- @objc
- func foo() { }
+ @objc func foo() {}
```

`--typeattributes new-line`

```diff
- @objc class Foo {}
+ @objc
+ class Foo { }
```

`--typeattributes same-line`

```diff
- @objc
- enum Foo { }
+ @objc enun Foo {}
```

### CODE REVIEW

**Comment by nicklockwood** [comment]
Another great PR, thanks!

**Comment by calda** [comment]
Ran this on the regression suite and noticed a couple of issues -- will make a follow-up PR with a couple of improvements.

**Comment by nicklockwood** [comment]
One problem I have with this rule is that I'm not sure `class` vs `func` is really the right criterion on which to vary the behavior. For example for the following cases I'd want "same-line":

```swift
@objc var foo: String

@objc func foo() {}

@obc(Foo) class ABCFoo() {}
```

But I'd want "new-line" for these:

```swift
@available(iOS 14.0, *) 
var foo: String

@available(iOS 14.0, *) 
func foo() {}

@available(iOS 14.0, *) 
class Foo() {}
```

And I'd not sure that varying based on the attribute name itself is right either, because then there are cases like this:

```swift
@obc(ABCFunctionWithAVeryLongName)
func functionWithAVeryLongName() {}
```

A possible solution would be a length-based system, e.g. `--attributewrap 10` where the argument is the maximum length of an attribute before wrapping.  What do you think?

**Comment by nicklockwood** [comment]
FYI, looking at the SwiftLint version of this rule, it also provides an option for attributes that should always be on the same line (e.g. IBAction): https://realm.github.io/SwiftLint/attributes.html

We should probably do the same as well (although I think a length threshold is more generally useful).

**Comment by nicklockwood** [comment]
> In the Airbnb Swift Style Guide specifically, our rule is that the attribute always goes on a separate like (even for short attributes like @objc).

For properties as well, or just functions and classes?

**Comment by calda** [comment]
It appears our rule only applies to functions and types. I'm not sure where we would land for properties.

**Comment by nicklockwood** [comment]
@calda OK, I'll probably add some more config for this, but I'll make sure your style guide is still supported.

**Comment by nicklockwood** [comment]
I found another case that maybe isn't handled correctly right now. If you have multiple attributes, e.g.

```swift
@objc @IBAction func foo {}
```

it becomes:

```swift
@objc
@IBAction
func foo {}
```

Is that what you'd expect it to be? I would probably prefer:

```swift
@objc @IBAction
func foo {}
```

Note that this is a somewhat esoteric example anyway, as I have a separate rule to remove the @objc here, which is redundant, but it can be reproduced with this test:

```swift
   func testMultipleAttributesKeptTogether() {
        let input = """
        @objc @IBAction func foo {}
        """
        let output = """
        @objc @IBAction
        func foo {}
        """
        let options = FormatOptions(funcAttributes: .prevLine)
        testFormatting(for: input, output, rule: FormatRules.attributes,
                       options: options, exclude: ["redundantObjc"])
    }
```

**Comment by calda** [comment]
I intended it to split them up into separate lines, but either seems reasonable since this is a fairly rare case.

**Pull request merged**
