### PR TITLE
Refactor Wrap Logic

### PR DESCRIPTION
**Pull request by AnthonyMDev**
This is a major refactor and conflicted with many of the most recent changes on `develop`. I am now in the process of cherry picking and rebasing all the recent changes on top of this. The main commits of this actual PR are ** 137f06b, bad798d, 647295a, & 285b7bb**. _I recommend that the current develop branch is not merged into master. Rather, after I have rebased all changes from `develop` on this branch, this branch should be merged into master and then `develop` should be re-created._

I've refactored the logic for wrapping and wrapping arguments. This breaks the calculation of the wrapping breakpoints out into another function that can be accessed in the `wrapArgumentsAndCollections()` function. This allows that function to take into account when and if the `wrap` rule is going to wrap the lines. It allows for more flexibility in the wrapping logic and helped me to fix a few other behaviors/bugs.

### CODE REVIEW

**Comment by nicklockwood** [comment]
@AnthonyMDev am I OK to start merging this, or are you still working on it?

**Comment by AnthonyMDev** [comment]
@nicklockwood  I'm still working on rebasing all of your other changes on top of it! I'll be done soon. But there are a few tests failing that I need you to look at. I think some of the failures are due to your changes on `develop`. I'll have a full write up of the issue shortly. Thanks for being so responsive!

**Comment by nicklockwood** [comment]
@AnthonyMDev 

> I'm still working on rebasing all of your other changes on top of it

If that's all that's left to do, I'm happy to take over. It's probably easier for me as I have the context on the changes I've made. I just wanted to avoid doing anything while you're still working and then causing further conflicts.

> I think some of the failures are due to your changes on develop

I'm not sure what this means. Tests on develop are currently passing.

**Comment by AnthonyMDev** [comment]
I'm getting close to done with it. Thanks for offering.

I think the test failures are due to interactions between my changes and yours. Looking into them now.

**Comment by AnthonyMDev** [comment]
@nicklockwood Rebase completed. Just about everything is passing. The only things not passing are two tests in `CommandLineTests` and `FormatterTests`. In both tests, it looks like there is an edge case in which we are removing a line break that shouldn't be removed now. It seems we don't have another test in the `RulesTests` that catches this edge case. I'm going to spend a little time trying to track it down, but if I don't track it down tonight, perhaps you can find it tomorrow. 

Thanks for working with me and being patient while I get this all cleaned up.

**Comment by nicklockwood** [comment]
@AnthonyMDev thanks - I'm pulling the changes now. I've found the bug with FormatterTests (it was a simple merge error).

**Comment by nicklockwood** [comment]
@AnthonyMDev OK so the other test that's failing is `testRegressionSuite()`, which is basically just a sanity check that the formatter isn't broken.

It works by running the formatter in --lint mode over a bunch of test projects to check there are no unexpected changes. To see those changes you can just remove the `--lint` argument in the test and then see what it actually did to the projects.

Looking at the diff, it seems like it's just fixed a bug in the indenting of some Euclid files that I'd previously missed, so I'll just commit those changes 👍

**Comment by AnthonyMDev** [comment]
Thanks so much! With the regression suite, I kinda guessed that we actually had a bug fix, but I wanted you to check it for sanity sake. :)

**Comment by nicklockwood** [comment]
@AnthonyMDev your changes have now landed in version 0.44.0. Thanks again for all your hard work 👍

**Pull request merged**
