### PR TITLE
Redraw icon for Big Sur

### PR DESCRIPTION
**Pull request by puls**
Not seeing the sources to the current icon available anywhere, I fired up Sketch and redrew it with the latest template.

|Old|New|
|-|-|
| AppIcon256 | icon_256x256 |

### CODE REVIEW

**Comment by nicklockwood** [comment]
@puls amazing! thank you.

Sorry to nitpick, but the `=` doesn't seem to be correctly aligned with the `}` - otherwise, great!

(I didn't draw the original - it was created by @markiv: https://github.com/nicklockwood/SwiftFormat/pull/654, but if you could provide the source files for your version I'll add them to the repo)

**Comment by puls** [comment]
@nicklockwood Try this one on for size. As for the source file, it's kind of a big blob, do you want it just in the repo alongside everything else or somewhere else?

**Comment by nicklockwood** [comment]
@puls maybe just upload it zipped to this PR discussion if it will let you? Then I'll figure out what to do with it.

**Comment by puls** [comment]
👍 

[SwiftFormat.zip](https://github.com/nicklockwood/SwiftFormat/files/5655579/SwiftFormat.zip)

**Pull request merged**
