### PR TITLE
Fix incorrect sample code

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by revolter** [comment]
I didn't expect for this to really be valid 🤣 I wonder how come no one fixed it before me.

**Comment by revolter** [comment]
Wait, is the correct value actually `tab` or `tabs`? 🙈

**Comment by nicklockwood** [comment]
They both work, but the value listed in the command line help is 'tab', so I guess I'll revert this actually.

**Comment by revolter** [comment]
See #600.

**Pull request merged**
