### PR TITLE
Add --config to pass config file from command line

### PR DESCRIPTION
**Pull request by NicholasFFox**
Partially address #75 - This does *not* add config file support in the Xcode extension. I'll add that when I get a bit more free time.

### CODE REVIEW

**Comment by nicklockwood** [comment]
Awesome! 👍

I've been holding off on adding this feature because I was having trouble deciding on a format for the file, and also whether it should be specified explicitly via a command, or whether it should look for a standard config file in the directory of the project being formatted (e.g. `swiftformat.yml`).

I'd still like to think about that a bit more, but this is definitely a good first step. Thanks again!

**Comment by NicholasFFox** [comment]
I definitely agree. I was torn between this approach and the standard config file. I think to make the Xcode extension work well, a standard config file is probably the best solution (similar to the way the old clang format plugin worked).

**Comment by nicklockwood** [comment]
@NicholasFFox supporting the Xcode extension is more challenging, because I'm not sure there's any way to get the path of the file being formatted (which would be needed in order to locate the config file), but @tonyarnold might have some ideas.

**Comment by tonyarnold** [comment]
Unfortunately, @nicklockwood is right. Xcode Source Editor Extensions are passed nothing in the way of project of filesystem context, so there's no way to get a project's configuration. 

I've started prototyping user preferences for the Xcode Extension as a result of the conversation in #69, but I haven't finished that yet. That work doesn't really answer the use case you're describing, but at least you could set defaults for your local account.

**Comment by dennisweissmann** [comment]
Are there any news here? :)

**Comment by davidgoli** [comment]
I would propose, given Xcode's notoriously bad support for plugins (breaking plugins with every release), any tool is more useful as a command-line tool that can be integrated with Git or run manually. Thus, if a config file works for Git but not as easily for Xcode, that's a win regardless.

I would love it if this tool had a config file option to be on parity with other languages (clang-format and prettier come to mind, and neither is designed primarily to integrate with any particular editor - that's rightly seen as an extra feature for perhaps an additional package to add to the base of a command-line tool.)

**Comment by nicklockwood** [comment]
@davidgoli most (perhaps all?) of the advantages of a config file can be achieved by putting a shellscript in the root of your project that calls SwiftFormat with whatever CLI arguments you want for your project. That's the solution I've adopted for my own projects.

**Comment by sunshinejr** [comment]
Hey @nicklockwood, what is the status of the issue? From what I've read you wanted to take time with deciding on the config format. I would love to have this in so I could help with implementation as well if needed @NicholasFFox.

**Comment by ethanjdiamond** [comment]
I'm going to second @sunshinejr. We'd like to version the config the same way we can with SwiftLint, Sourcery etc. They seem to have coalesced around YAML, which I think would work great here as well.

**Comment by nicklockwood** [comment]
@NicholasFFox well it took a little while, but this is now merged on the develop branch.

I'm going to make a few changes, such as switching over to the same config file format used by the Xcode Source Editor Extension, but this should land in the next release.

**Pull request merged**
