### PR TITLE
Update Credits

### PR DESCRIPTION
**Pull request by aerobounce**
I made a plugin for Sublime Text 3 that utilizes SwiftFormat.
[Sublime-Swift-Format](https://github.com/aerobounce/Sublime-Swift-Format)

Working like a charm and waiting for merge on Package Control (Official Package Manager for Sublime Text).
I don't think I have a day that I don't use SwiftFormat.
Let me say, thanks for your constant work!

### CODE REVIEW

**Comment by aerobounce** [comment]
Simplified commit message.

**Comment by nicklockwood** [comment]
This looks great! Do you want to add it to the installation instructions too? I'm not sure many people will notice it if it's just in the credits at the bottom.

**Comment by aerobounce** [comment]
Sounds cool! If you are ok with that, definitely yes, please!
And you are right, people might not notice the plugin exists.

**Comment by aerobounce** [comment]
Ah, You meant me to do that! Sorry, I'd misunderstood.
Please let me do that another time.

Thanks for merging.

**Comment by nicklockwood** [comment]
No problem, I've added it now :-)

**Comment by aerobounce** [comment]
You've done it but just not committing yet? If that's so, thanks!

But in case I'm making another misunderstanding by myself, I've made commit like this: https://github.com/aerobounce/SwiftFormat/commit/9a8f9bf09e60818809b3bce2a46592f32287543c
I'm ready to create another PR in that case.

**Comment by nicklockwood** [comment]
@aerobounce it's done and committed on the develop branch.

**Comment by aerobounce** [comment]
Cool. Thanks for this 😄

**Pull request merged**
