### PR TITLE
Add wrapMultilineConditionalBraces rule

### PR DESCRIPTION
**Pull request by calda**
This PR adds a `wrapMultilineStatementBraces` rule, which was discussed briefly in #665

When the `wrapMultilineStatementBraces` rule is enabled, the opening brace for `if` / `guard` statements and `func` declarations will wrap to the next line. This is the style we use in the [Airbnb Swift Style Guide](https://github.com/airbnb/swift).

```diff
  if foo,
-   bar {
    // ...
  }

  if foo,
+   bar
+ {
    // ...
  }
```

```diff
  guard foo,
-   bar else {
    // ...
  }

  guard foo,
+   bar else
+ {
    // ...
  }
```

```diff
  func foo(
    bar: Int,
-   baz: Int) {
    // ...
  }

  func foo(
    bar: Int,
+   baz: Int)
+ {
    // ...
  }
```

### CODE REVIEW

**Comment by calda** [comment]
@nicklockwood This PR reapplies #668 to `develop` instead of `master` 👍

**Comment by calda** [comment]
Ah I see that you fixed this in [`b9bad49`](https://github.com/nicklockwood/SwiftFormat/commit/b9bad4944d2f72ed747ee4ceb0b6a26b4b07bf44), thanks!

**Comment by nicklockwood** [comment]
@calda I notice that there's a bit of a conflict between this rule and the `--xcodeindentation` option, specifically for this case:

```swift
guard self == .bar
     else {
         return ""
}
```

Normally, with `--xcodeindentation disabled` this would be indented like this:

```swift
guard self == .bar
else {
    return ""
}
```

In which case the `wrapMultilineStatementBraces` rule doesn't engage because the `else` isn't indented. But with  `--xcodeindentation enabled`, the indented `else` causes the `{` to wrap, which seems a bit weird.

```swift
guard self == .bar
     else
{
    return ""
}
```

Is this the behvior that you wanted? If not, I can special-case the orphaned `else`.

**Comment by calda** [comment]
Aah interesting, I hadn't tried this with `--xcodeindentation enabled`. Patching this issue with a special-case sounds reasonable 👍

**Pull request closed without merging**
