### PR TITLE
`modifierOrder` option documentation clarification

### PR DESCRIPTION
**Pull request by hamtiko**
Related: https://github.com/nicklockwood/SwiftFormat/issues/849

Added an example syntax for the `modifiersOrder` option and separate section about default order by groups in the Rules.md doc.

### CODE REVIEW

**Comment by nicklockwood** [comment]
This is very helpful - thank you!

The contents of Rules.md are automatically generated from the Examples.swift file though, so the example should be added there too otherwise the metadata unit tests will fail.

**Comment by hamtiko** [comment]
thanks @nicklockwood, just noticed it with check fails. Changed it to use `help` param of OptionDescriptor.  Do you think this is clear enough?

**Comment by hamtiko** [comment]
thanks @nicklockwood, just noticed it with check fails. Changed it to use `help` param of option in OptionDescriptor.  Do you think this will be clear enough?

**Review by calda — APPROVED** [review]
Thanks! This is really helpful. I like how the Rules.md content is generated automatically from the `_FormatRules.defaultModifierOrder` value! I didn't realize we could include dynamic values using string interpolation here.

**Pull request merged**
