### PR TITLE
Add option to specify --lintonly rules

### LINKED ISSUE #865: Add an option to print warning for specific rule in format mode too
My specific use case is about the unusedArguments rule. I want to get a warning about unusedArguments but I don't want to format them, as I often hit build (which triggers formatting) during coding.

This can be worked around by having 2 swiftformat.yaml files and calling swiftformat in build phase twice but it would be nicer to only maintain 1 rules file.

### PR DESCRIPTION
**Pull request by Cyberbeni**
Resolves #865 

Fixed project, so the command line tool uses adhoc signing for debug build and running it locally also uses the debug build. (Archive will still use the release configuration with the currently configured signing)

Still needs tests

### CODE REVIEW

**Comment by nicklockwood** [comment]
@Cyberbeni this is still marked as a draft. Are you planning to work on it more? Are you waiting for me to review?

**Comment by Cyberbeni** [comment]
I'll probably have time to finish it this weekend but I can't make any guarantees.

Tests are still needed (and the help length test currently fails because it's more than 80 characters), otherwise it seems to be working fine, so the current changes can be reviewed.

**Comment by Cyberbeni** [comment]
I realized during writing the tests that if I specify `--lintonly foo` in the command and specify `--lint` in the config, it will be already converted to `--disable foo` for the merging. Is that a supported use case, or should I leave it as is?

**Comment by Cyberbeni** [comment]
I have the "Allow edits by maintainers" checked, please reword/wrap the help text as you see fit. @nicklockwood

**Pull request merged**
