### PR TITLE
Windows: correct the XML tag for the installer manifest

### PR DESCRIPTION
**Pull request by compnerd**
Correct the closing tag from `Directory` to match the opening tag of `StandardDirectory`.

### CODE REVIEW

**Comment by compnerd** [comment]
Hey @nicklockwood, sorry about the churn here.  This repairs the MSI building, though I'm not 100% certain about the release steps.  Would it be possible by any chance to get a 0.5.13 rolled with this?  I think that there will be one more change that I would like to get sorted out in the medium term (packaging the runtime into the directory to avoid the ABI issues).  That would allow building with a particular version (e.g. the latest release) rather than for various versions.  That is dependent on the MSM packaging that I hope to get to soon.

**Comment by nicklockwood** [comment]
@compnerd no problem - and thanks again for doing this!

I tried running the Windows Release action and it succeeded but didn't produce any artifacts - perhaps I'm missing something? https://github.com/nicklockwood/SwiftFormat/actions/runs/5326452188

**Comment by compnerd** [comment]
https://github.com/nicklockwood/SwiftFormat/actions/runs/5326452188/jobs/9648512696 ...
oh no, it is colliding the two builds :-(.

That should hopefully be easy to fix.  In the mean time, if you go to "Releases", there should be a draft release waiting for you to make public.  When you do so, it should just show up on the release list!

**Comment by nicklockwood** [comment]
@compnerd sorry for not getting back to you sooner. I'm not sure I want to make a 0.5.13 just for windows support since there's no reason to make everyone else upgrade, but rather than wait I've attached a swiftformat_windows.zip download to the existing 0.5.12 release.

The zip contains both the exe and msi files - hopefully that's the right approach? If not I can make them separate downloads.

**Comment by compnerd** [comment]
@nicklockwood sure, that makes sense, though separate downloads would be better.  If you use the MSI, you don't need the exe - the installer will take care of it.

**Pull request merged**
