### PR TITLE
AppKit changes for the wrapper app

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR builds on the work done by @VinceBurn in #211. 

Primarily, it moves all configuration of table view cells into the main storyboard. 

It also includes a few other minor fixes/changes:

- Ensures the code signing details are only stored at the Xcode project level - they were duplicated on the macOS app/extension targets.
- Makes the "Rules" tab the initial tab, and renames the "SwiftFormat" tab to "About".
- Removes some unused/unnecessary code.

### CODE REVIEW

**Comment by tonyarnold** [comment]
To be clear, I think this still needs UI work - more explanatory text about what the rules are setting, and how and when they'll affect SwiftFormat's output. It would also be _really_ great to be able to provide descriptions, examples and a localised name for each rule. Not sure how you'd like to approach that @nicklockwood - happy to be guided here.

**Comment by nicklockwood** [comment]
@tonyarnold understood. I might be able to rig up some kind of script to generate inline docs automatically from the README file.

Localization will be a little more challenging since I'm only fluent in English (Traditional) and English (Simplified), but if I can get a technical solution in place maybe the community can help out with the translations :-)

Thanks again for all your help 👍

**Comment by VinceBurn** [comment]
@nicklockwood, @tonyarnold 
>  more explanatory text about what the rules are setting, and how and when they'll affect SwiftFormat's output. It would also be really great to be able to provide descriptions, examples and a localised name for each rule. Not sure how you'd like to approach that

While implementing I've been juggling with the idea of having a: RuleDescriptor and an OptionDescriptor for that purpose. 
Option could have a link toward the rule(s) they affect, which would permit to show a UI where option affecting a rule could be group with them (when there is a 1 to 1 relation) and description could be presented in a tool tip or by selecting an "info" button.
Those object could also be use to augment the help command of the command line tools.

The down side we would need to create an instance for each rules and 1 for each option.

**Comment by tonyarnold** [comment]
Alternately, we could provide a list of localised strings that follow a set pattern like `\(rule.name).description` and `\(rule.name).displayName`?

**Comment by nicklockwood** [comment]
For the rule documentation and/or metadata like associated options, I can think of a few solutions:

1) Add a bunch of methods or vars to the Rules class using a naming scheme like `<ruleName>Description` and `<ruleName>Options` and then grab them using the Obj-C runtime, as I do for the rules themselves. This wouldn't really help with localization though.

2) Switch from using a method per rule to a class or object instance per rule, which would then allow arbitrary metadata to be added. That's a big refactoring job though, and who knows what affect it will have on performance, etc. Also doesn't really help with localization.

3)  Use a script to extract the existing descriptions from the README. I basically already have something like that in one of the unit tests anyway, but it's a bit fragile. Also doesn't support localization and doesn't help with other metadata like options.

4) A separate strings file with the localizations as Tony suggests. That isn't a great solution for associating the options, which should really be done in code somehow so it can be validated statically, but it's probably the only viable solution for localizing the text.

As an aside: for display names, I can probably do the English ones by just transforming the rule name from camel case to space-delimited automatically. Not sure if/how that helps with localized names though.

**Comment by VinceBurn** [comment]
Option 5.
I was thinking something like this:
```swift
struct RuleDescriptor {
    typealias ID = String
    let id: ID
    let name: String
    let shortDescription: String
    let longDescription: String
    let codeExample: String
}

struct OptionDescriptor {
    enum OptionType {
        case binary
        case list([String])
        case freeText
        case listOrFreeText([String])
    }

    let id: String
    let name: String
    let shortDescription: String
    let longDescription: String

    let optionType: OptionType
    let impactRules: [RuleDescriptor.ID]
}
```
That would not be use by the parser at all, so not that much refactoring and no performance cost at parsing, but could express the requirement for the help and for the Option selection for the MacOS app.
The ID could be use as the stored key in UserDefaults.

**Comment by nicklockwood** [comment]
@VinceBurn how would the instances of these descriptor structs be created? Would they be hard-coded or deserialized from some kind of configuration file?

How would we ensure that they were kept in sync with the rules (e.g. if a rule or option is added, removed or renamed, what would ensure that the appropriate changes are also made to the descriptors)? How can that be automated, or at least automatically verified?

It was really these questions that I was attempting to address with my suggestions. The actual properties stored in the descriptor structs is less critical at this point.

Keeping stuff like code and docs in sync is generally a big headache with this kind of project, which is why I have stuff like unit tests that fail if a rule name can't be found in the README.

I'd like to try to limit the number of ways I can can screw up by using techniques such as introspection to get the rule names so I don't have to maintain a separate list, or by colocating docs and rules logic so it's less likely that one will be updated without the other.

**Comment by VinceBurn** [comment]
@nicklockwood very good concern, I like your thinking.
I'm not sold on descriptor here and I'm bouncing the idea to see the pros and cons.

For creation of descriptor, hard coded in a code file or in a config file, I think it is an implementation detail. I would go in code first and move to a config file late if needed.
For keeping in sync rules and options with descriptor, the ID use for descriptor should be the name of the rules / options so we can validate that each rules and options exist in Unit Test. Options already have a separate list called `formatArguments` in the CommandLine.swift file that need to be maintain. An OptionDescriptor list would replace that list.
If we have Rule descriptor that state that it rely on 3 options, we could also test that those options exist.

**Pull request merged**
