### PR TITLE
Xcode source editor extension

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR introduces an Xcode Source Editor Extension for SwiftFormat.

It works, but there are a few things still left to sort out, namely:

#### Xcode Source Editor Extension
- [x] Handle formatting just the user's selection (I might need to expand the selection to include the entire lines of selections so that there's enough context for the formatter)
- [x] Restore the user's previous selection
- [x] Handling tabs for indentation (currently it respects the user's indentation settings, so long as they use spaces)
- [x] Version information is manually set - I think it's wise to keep the version of the framework, app and app extension the same, so this should be set somewhere central to reduce maintenance

#### Hosting Application
- [x] Provide a simple explanatory UI outlining how to enable and use the extension, as well as set a keyboard shortcut

To use this PR, you will need to archive and export the application target using a proper certificate. Unsigned or improperly signed application/application extensions are not loaded by Xcode 8.x.

#### 🚧 Download 🚧 

Here's a preview release: [SwiftFormat for Xcode 0.12.zip](https://github.com/nicklockwood/SwiftFormat/files/521015/SwiftFormat.for.Xcode.0.12.zip)

You'll need to enable the extension in System Preferences → Extensions:

screen shot 2016-10-05 at 21 01 46

After relaunching Xcode, you should be able to set a keyboard shortcut for this as follows:

screen shot 2016-10-06 at 13 32 51

No promises, ensure you're not working with uncommitted code, etc, etc.

### CODE REVIEW

**Comment by tonyarnold** [comment]
@nicklockwood do you have any aversion to using `agvtool` for setting version numbers for all of the targets? Not sure if you've used it before, but it would just take a few small tweaks to the project file (that I'd make as part of this PR). 

There are docs available here: https://developer.apple.com/library/content/qa/qa1827/_index.html

But the basic gist of it is:

```
xcrun agvtool new-marketing-version 0.13.   // Bumps the user visible CFBundleShortVersionString to this string
xcrun agvtool next-version -all    // Bumps the CFBundleVersion to 2
```

I could setup something linked to Git if you'd prefer, I just want to ensure all of the binary versions track each other.

**Comment by nicklockwood** [comment]
@tonyarnold no, no objection.

**Comment by tonyarnold** [comment]
OK, I think once #43 is sorted, this is ready for a review and (hopefully) a merge. Thanks for all the fixes along the way, @nicklockwood!

**Comment by nicklockwood** [comment]
@tonyarnold awesome, thanks for doing this. I'll look into that trailing linebreak issue and then see about getting this merged.

**Comment by tonyarnold** [comment]
👍 I needed this for myself, too. Thanks for making the library/tool!

**Comment by nicklockwood** [comment]
@tonyarnold I can't see "Xcode Source Editor" in System Preferences > Extensions on El Capitan. Does this only work on Sierra?

I found some advice suggesting you need to do this on 10.11, but it didn't work for me:

> If you're running this on OS X 10.11 like I am, you'll need to run sudo /usr/libexec/xpccachectl and reboot before Xcode will even attempt to load your extensions. It has something to do with new SDKs being installed and the XPC service in El Capitan not expecting it.

**Comment by tonyarnold** [comment]
It should definitely be working under 10.11, but Source Editor Extensions are notoriously finicky there. I'm not sure I can provide more advice than to make sure the app is installed in `/Applications`, and that you've run those commands and rebooted. 

I believe that having the 8.1 betas interferes with Source Editor Extensions under 10.11 as well. It's working fine without any of those dramas under Sierra.

**Comment by nicklockwood** [comment]
@tonyarnold I'll keep trying to get it to work. In the meantime, it might be helpful if the extension app detected your macOS version and provided different instructions accordingly.

**Comment by tonyarnold** [comment]
The other thing to check is that you're signing the exported Application and Extension. If they're improperly signed, Xcode won't load the appex.

**Comment by nicklockwood** [comment]
Hey, sorry for the delay again. I never got it working on El Cap, but I took the plunge and upgraded to Sierra and it's working great.

It you wouldn't mind rebasing against 12.1, I'll pull this in.

Let me know what sort of attribution you'd like in README, etc.

**Comment by tonyarnold** [comment]
OK, rebased and 👍 

In terms of attribution, just something small and specific to the Xcode extensions — you did all of the heavy lifting, and this extension still isn't perfect. I just wrapped it up into the correct format, and implemented some simple selection restoration. I'm hopeful others will improve this logic in the future.

**Comment by tonyarnold** [comment]
Woohoo! Thanks @nicklockwood!

**Pull request merged**
