### PR TITLE
Group options with associated rule #353 

### PR DESCRIPTION
**Pull request by VinceBurn**
#353  

Hi @nicklockwood ,

I've put this together, if you like the end result, all that is left to do is to clean up the code mess I've made.

### CODE REVIEW

**Comment by nicklockwood** [comment]
@VinceBurn looks pretty good (I've only looked at the app so far, not the code).

One thing that does seem very apparent now that I see the shared options is that really each option only has a single rule that it naturally relates to.

Allman Braces belongs with the indent rule.
Comments belong with the braces rule.
Linebreak Character belongs with the linebreaks rule.
Trim White Space belongs with the trailingSpace rule.

The fact that these options are used incidentally by other rules is just an implementation detail. I don't think there is any good reason to expose this to the user.

I suggest we get rid of the Options tab altogether.

**Comment by nicklockwood** [comment]
We also need to decide what to do about the "Infer options checkbox". It's currently broken as it only disables the options on the Options tab, not the inline ones in Rules. If we get rid of the Options tab, it makes sense just to move it to the top of the Rules tab.

**Comment by nicklockwood** [comment]
@VinceBurn I'm also not 100% convinced it wouldn't look better if the options were hidden by default with a disclosure arrow. Especially when rules are disabled, it seems strange that the options are still visible and enabled.

**Comment by VinceBurn** [comment]
Hi @nicklockwood ,
> The fact that these options are used incidentally by other rules is just an implementation detail. I don't think there is any good reason to expose this to the user.

If the option affect the "secondary" rules when its primary rule is not active, I think we need to expose that fact, so the user can know that this option is still affecting a rule.

> @VinceBurn I'm also not 100% convinced it wouldn't look better if the options were hidden by default with a disclosure arrow. Especially when rules are disabled, it seems strange that the options are still visible and enabled.

If we gray them out (like when the Infer option is ON) when the rule is disable I think that would be good enough.

**Comment by nicklockwood** [comment]
@VinceBurn 

> If the option affect the "secondary" rules when its primary rule is not active, I think we need to expose that fact, so the user can know that this option is still affecting a rule.

I'm thinking that if you have disabled the primary rule that an option relates to, you probably don't care about that option, and that instead of letting you set it explicitly, we should just use the inference mechanism to determine an appropriate value for it:

Allman Braces - clearly if you have disabled the braces rule, you don't want SwiftFormat to rewrap braces, so it makes sense that any rules that do happen to rewrap as part of their function should just follow what the rest of the file is doing.

Linebreak Character - if you don't want SwiftFormat to make linebreaks consistent, you probably don't care about linebreaks at all,  but using whatever the majority of the file uses should be fine.

Trim White Space - again, if you don't want white space explicitly trimmed, it doesn't really matter if some rules trim it for lines that they insert.

Comments - this one is a bit tricky because the option mainly exists to work around a bug, but defaulting it to false is probably safe if you don't want explicit indenting enabled anyway.

**Comment by nicklockwood** [comment]
@VinceBurn I'll need to add a few bits of logic to support this mechanism.

I think the first thing is probably splitting rule options into regular and "shared" options, where an option can only be in the regular options set for one rule.

The second thing will be refactoring the inference mechanism so it can be used to infer the values for individual options instead of the entire options struct.

**Comment by nicklockwood** [comment]
@VinceBurn I've pushed the sharedOptions logic to develop.

**Comment by nicklockwood** [comment]
@VinceBurn any update on this? Just checking you aren't waiting on me for something.

**Comment by VinceBurn** [comment]
Hi @nicklockwood, I didn't had the time to fully check and grasp the change you've made, but I don't think I need more. Next week I'm on vacation so I will probably have some time to advance on this.

If we put everything in the same tab, do you think that we should repurpose the newly empty tab to present option that don't affect the Xcode extension? That would allow to modify and save a file that could be use to share settings for the extension between team members, but also to use the same output for script that use Swiftformat, without the need to manually edit it after saving? If you think it is a good idea, I think we should address it in a different issue / pull request.

**Comment by nicklockwood** [comment]
@vinceburn that does sound like a useful feature, but as you say it should be a separate PR.

**Comment by nicklockwood** [comment]
@VinceBurn hey, FYI I just pushed the new inference logic to develop. Now, if the list of enabled rules do not include a non-shared reference to an option, the option's value will be inferred from the source file instead of using the user-provided value.

For example, let's say that I have enabled the `blankLinesBetweenScopes` rule, but I haven't enabled the `linebreaks` rule. The `blankLinesBetweenScopes` rule uses the `linebreak` character defined in the format options but it isn't the owner of that rule, so it's not obvious to the user that they'd need to set it.

Previously if the user forgot to set the `linebreak` option, `blankLinesBetweenScopes` would end up inserting the default linebreak character of `\n`, which might not match what the rest of the file is using.

Now however, SwiftFormat will ignore the `linebreak` option specified in the config, and will infer its value by looking at the file contents. This ensures that rules won't introduce formatting inconsistencies because the user forgot to set an option that they weren't aware they needed to.

The user-specified value for `linebreak` will only be used if the user enables the `linebreaks` rule (in which case all linebreaks in the file will be updated, so there is no problem with consistency).

**Comment by VinceBurn** [comment]
Hi @nicklockwood
I just realize that I forgot to migrate the infer option.
I will look into that later today.

**Comment by nicklockwood** [comment]
@VinceBurn this is looking pretty great so far - thanks!

**Comment by VinceBurn** [comment]
Hi @nicklockwood 

I've add back the infer options and rebase on develop.

**Comment by nicklockwood** [comment]
@VinceBurn works great, thanks!

**Pull request merged**
