### PR TITLE
Add Redundant type rule

### PR DESCRIPTION
**Pull request by facumenzella**
### Why?

> This PR tackles https://github.com/nicklockwood/SwiftFormat/issues/469

### What?

The idea is to go from this:

```swift
let rect: CGRect = CGRect(...)
```

to this:

```swift
let rect = CGRect(...)
```

### CODE REVIEW

**Comment by namolnad** [comment]
@facumenzella after scanning the code, I don't think this is currently an option, but wanted to double check. Does this rule have the ability to alter `let rect: CGRect = CGRect(...` to `let rect: CGRect = .init(...`?

**Comment by nicklockwood** [comment]
@facumenzella no,  but this is something I'd like to add as an option. Feel free to open a new issue to track it.

**Comment by facumenzella** [comment]
@nicklockwood it does not support that, but I guess it won't be that hard to add.

**Comment by namolnad** [comment]
Thanks @nicklockwood @facumenzella, I've added #816 to track this.

**Pull request merged**
