### PR TITLE
Add organizeDeclarations rule

### PR DESCRIPTION
**Pull request by calda**
This PR adds a new disabled-by-default `organizeDeclarations` rule, based on the discussion in #683.

Declarations in `class`, `struct`, and `enum` bodies are sorted based on their visibility (e.g. `public` declarations come before `private` declarations) and type (e.g. within individual categories, properties come before functions).

  - To make it easier to inspect and move entire  _declarations_ (rather than just individual tokens), this PR also adds a new declaration parser (`Formatter.parseDeclarations() -> [Declaration]`). One we have a list of declarations inside a given type, it's reasonably straightforward to sort those declarations based on different features (e.g. their visibility).

```diff
  public class Foo {
-     public func c() -> String {}
-
-     public let a: Int = 1
-     private let g: Int = 2
-     let e: Int = 2
-     public let b: Int = 3
-
-     public func d() {}
-     func f() {}
-     init() {}
-     deinit() {}
 }

  public class Foo {
+
+     // MARK: Lifecycle
+
+     init() {}
+     deinit() {}
+
+     // MARK: Public
+
+     public let a: Int = 1
+     public let b: Int = 3
+
+     public func c() -> String {}
+     public func d() {}
+
+     // MARK: Internal
+
+     let e: Int = 2
+
+     func f() {}
+
+     // MARK: Private
+
+     private let g: Int = 2
+
 }
```

This rule has several configuration points:

Option | Description
--- | ---
`--categorymark` | Template for category mark comments (defaults to `MARK: %c`)
`--beforemarks` | Declarations placed before first mark (e.g. `typealias,struct`)
`--lifecycle` | Names of additional Lifecycle methods (e.g. `viewDidLoad`)
`--structthreshold` | Minimum line count to organize struct body (defaults to `nil`)
`--classthreshold` | Minimum line count to organize class body (defaults to `nil`)
`--enumthreshold` | Minimum line count to organize enum body (defaults to `nil`)

### CODE REVIEW

**Comment by nicklockwood** [comment]
@calda this looks amazing, thanks! There's a bit too much going on here for me to review it line-by-line, so I'll land it as is and then iterate if I find any problems.

**Comment by nicklockwood** [comment]
@calda what was the reason for the `rewritesEntireFile` property? What happened without it? Was it just that the line tracking didn't work correctly?

**Comment by calda** [comment]
> so I'll land it as is and then iterate if I find any problems.

Happy to take on responsibility for fixing bugs / issues with this new rule.

> what was the reason for the rewritesEntireFile property? What happened without it? Was it just that the line tracking didn't work correctly?

Without `rewritesEntireFile`, the formatter was getting stuck in an infinite loop. It was detecting conflicting changes between the `organizeDeclarations` rule and any other rules that were being triggered. It seemed like it was trying to run the rules again until it no longer detected conflicts, which was causing it to run and rerun the rules forever. Not sure if a `rewritesEntireFile` flag is the best solution for this problem, but it does fix the issue I was hitting.

**Comment by nicklockwood** [comment]
@calda I've added a unit test to the develop branch that demonstrates a bug (or possibly a couple of bugs) I've found in the `organizeDeclarations` rule.

It seems to work fine on the first pass, but when the rule is run again on a codebase that has already had its declaration organized, the rule removes many of the `// MARK: ...` comments that were added the first time. You can see this in the unit test where the `// MARK: Internal` is removed, but I've also reproduced it with real-world projects.

I'm wondering if this bug might explain the issue you were seeing before where applyRules never settled on a stable output?

Separately, there seems to be a bug affecting the `testFormatting()` test infra function where `FormatRules.all(except: exclude)` just returns the input instead expected output. I suspect this is related to the `rewritesEntireFile` logic you added (which can maybe be removed when the first bug is fixed)?

**Comment by calda** [comment]
Thanks for flagging, I'll take a look!

Interestingly, it seems like most of the tests that were passing on my work branch for this PR are now failing on `develop` (even when I checkout the specific merge commit [`459de50`](https://github.com/nicklockwood/SwiftFormat/commit/459de50c52091e52af4cec84b2dc1f16b672604e)). Something must have subtly changed on `develop` between when this was branched and merged 🤔

**Comment by nicklockwood** [comment]
Hmm, it might be that some of my refactoring broke something - if so you can disregard and I'll fix it. It would be helpful if you could commit any of your tests that were previously working and now fail.

**Comment by calda** [comment]
All good! I have a fix locally for that specific issue. I'm also fixing some issues with `parseDeclarations()`. PR coming shortly!

**Comment by calda** [comment]
It also looks like we can get rid of the `rewritesEntireFile` flag! 🎉 You were totally right about this:

> I'm wondering if this bug might explain the issue you were seeing before where applyRules never settled on a stable output?

**Comment by nicklockwood** [comment]
@calda is there a particular reason why you treat class methods specially, but not class properties? Why is there no `classProperty` or `classPropertyWithBody` case in `DeclarationType`?

**Comment by calda** [comment]
> Ah, I see that stored class properties are illegal in Swift (TIL). However computed class properties are not, so classPropertyWithBody would still be a valid case.

Ah I didn’t realize `class` properties existed! This is just an oversight, should be easy to fix.

**Pull request merged**
