### PR TITLE
Log skipped files

### PR DESCRIPTION
**Pull request by allewun**
I found this useful when making sure my excluded files were properly setup.

### CODE REVIEW

**Comment by nicklockwood** [comment]
I think there's a case for exposing this in the verbose logging, but having it on all the time is a bit noisy

**Comment by allewun** [comment]
@nicklockwood Yep you're right. I've added a check for the verbose flag.

**Comment by nicklockwood** [comment]
Sorry this didn't make it into the latest release, but I haven't forgotten about it - just thinking about the API.

**Comment by nicklockwood** [comment]
@allewun this will be included in the next release. Sorry for the wait!

**Comment by nicklockwood** [comment]
@allewun this feature has landed in version 0.35.3.

**Pull request merged**
