### PR TITLE
Rename noFileID rule to fileMacro, support preferring either #file or #fileID

### PR DESCRIPTION
**Pull request by calda**
[This discussion](https://forums.swift.org/t/file-vs-fileid-in-swift-6/74614) on the Swift Evolution forums shows that there isn't a clear consensus on whether or not `#file` or `#fileID` will be preferred long-term.

This PR renames the `noFileID` rule to `fileMacro`, and adds support for preferring either `#file` or `#fileID`.

### CODE REVIEW

**Comment by nicklockwood** [comment]
@calda are these actually macros? I'm not sure what the general term for `#identifiers` is in Swift, but they predate macros

**Comment by calda** [comment]
Yes, they're considered macros now: https://developer.apple.com/documentation/swift/macros

**Comment by nicklockwood** [comment]
I think this is reasonable given the information we have so far, but tbh it might make more sense to wait and find out the conclusion of [the discussion](https://forums.swift.org/t/file-vs-fileid-in-swift-6/74614) before shipping this, because it feels like something where there will be a *right* way and a wrong way, as opposed something that should be left to individual preference

**Comment by calda** [comment]
To me, there not being a clear consensus today is a great reason _why_ we would have a format rule for this. You may prefer `#fileID`, and I may prefer `#file`, and until one is deprecated there isn't an intrinsic technical reason to prefer one over the other.

My gut feeling is that the status quo (neither being deprecated) will stay the same for quite a while. (Would love to be wrong about this! It just seems too low priority and contentious to me.)

So, to me, it doesn't seem necessary to intentionally delay releasing this. Today is when it's most useful :) If this changes one day it seems fine to deprecate the rule at that point.

**Pull request merged**
