### PR TITLE
Update README.md

### LINKED ISSUE #161: cocoapods integration instructions not correct.
In the tutorial, the path is incorrect. The path should be `${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat .` instead of `"${SRCROOT}/Pods/SwiftFormat/CommandLineTool/swiftformat"`. I will create a PR to fix this.

### PR DESCRIPTION
**Pull request by RishabhTayal**
Fixes #161

### CODE REVIEW

**Comment by nicklockwood** [comment]
Can you put the quotes back and remove the . again? The quotes are necessary if the project directory contains a space, and the description of this line is that it's a path, so it shouldn't include the argument for formatting.

**Comment by RishabhTayal** [comment]
I don't think we need the quotes. I have space in my project and it's working without quotes. I actually doesn't work with quotes. You can also refer to how `swiftlint` integration is documented [here](https://github.com/realm/SwiftLint/blob/master/README.md#using-cocoapods). Also I added `.` so that it will run the command `swift format .` as a build script every time you compile.

**Comment by nicklockwood** [comment]
> It actually doesn't work with quotes

Thats's odd. The swiftlint example in the doc you linked to also uses quotes:

     "${PODS_ROOT}/SwiftLint/swiftlint"

**Comment by RishabhTayal** [comment]
Let me double check if the command works with `"` or not.

**Comment by RishabhTayal** [comment]
I can confirm that the script won't work if there are `"`. This is what I have in the run script and it works without quotes. After adding quotes it breaks.

`${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat .`

**Comment by RishabhTayal** [comment]
@nicklockwood, here is another discovery I made. The following scripts will work in the run script. `"` is actually nice to have. I will change my PR if you can confirm if everything looks good in the below examples.

`"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" "." "--disable" "trailingCommas,numberFormatting"`
`"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" "."`
`"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat"`
`${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat .`

**Pull request merged**
