### PR TITLE
Add rule to convert `forEach { ... }` calls to for loops

### PR DESCRIPTION
**Pull request by calda**
This PR adds a new disabled-by-default `forLoop` rule which converts `.forEach { ... }` calls to use for loops instead:

```diff
  let strings = ["foo", "bar", "baaz"]
- strings.forEach { placeholder in
+ for placeholder in strings {
      print(placeholder)
  }

// Supports anonymous closures!
- strings.forEach {
+ for string in strings {
-     print($0)
+     print(string)
  }

- foo.item().bar[2].baazValues(option: true).forEach {
+ for baazValue in foo.item().bar[2].baazValues(option: true) {
-     print($0)
+     print(baazValue)
  }

// Doesn't affect long multiline functional chains ✅
placeholderStrings
    .filter { $0.style == .fooBar }
    .map { $0.uppercased() }
    .forEach { print($0) }
```

The secret sauce here for converting from anonymous closures to non-anonymous closures is the [`GrammaticalNumber` package](https://github.com/Cosmo/GrammaticalNumber), which I added as a dependency.

### CODE REVIEW

**Comment by calda** [comment]
Seems I need to tweak how the dependency is set up. Probably need to configure it in the Package.swift and not just the Xcode project.

The dependency is just a single file so it may be easier to just copy into the repo instead of adding it as an SPM dependency. Any preference @nicklockwood?

**Comment by nicklockwood** [comment]
@calda yeah, I'd definitely prefer to avoid the package dependency as it complicates the build process.

**Comment by nicklockwood** [comment]
(This is a great idea for a rule btw - and something I've wanted to add for a while 👍)

**Comment by calda** [comment]
Seems like the code coverage job is broken.

I see the windows CI job is uploading code coverage data, but not actually running any tests (it runs some test target but that target includes 0 actual test cases). Maybe that's what's breaking the code coverage reporting?

**Comment by calda** [comment]
CI is passing now @nicklockwood

**Comment by calda** [comment]
Ran this rule on our codebase and found some issues. Will post fixes in follow-up. Some examples include:

image

image

image

silly case where the code is using `return void` but which breaks when converted to `continue`:

image

**Comment by calda** [comment]
I'm also thinking we want to add linebreaks when converting from a single-line `forEach`, so convert:

```swift
placeholderStrings.forEach { print($0) }
```

to:

```swift
for placeholderString in placeholderStrings {
  print(placeholderString)
}
```

**Comment by nicklockwood** [comment]
I'm thinking single-line loops should maybe stay on one line. And/or there should be an option to not convert one-liners 🤔

**Comment by calda** [comment]
An option makes sense to me

**Comment by nicklockwood** [comment]
@calda this rule landed in 0.53.0. FYI I made a few changes:

* Single line forEach is no longer converted by default. you can enabled that with an option
* Single line foreach is not wrapped when it's converted - there's a new wrapLoopBodies rule for that instead
* I rewrote the GrammaticalNumber logic to be simpler and handle more cases. You may find it behaves slightly differently with respect to your codebase

**Comment by calda** [comment]
Thanks for letting me know! I updated our tools to reflect the new options (https://github.com/airbnb/swift/pull/255)

**Pull request merged**
