### PR TITLE
Technical/wrap options

### PR DESCRIPTION
**Pull request by Parabak**
Hi 👋, 

as agreed I've tried to implement `--conditionswrap`. I hope that I got your idea in the right way 😅
At least this option does what I'd expect.

Looking forward to hearing from you.

best, Alex.

### CODE REVIEW

**Comment by nicklockwood** [comment]
@Parabak thanks! Yes, this is pretty much what I had in mind. There are a few tweaks I want to make (as well as adding support for function arguments, etc),  but I'll probably land this as-is and then stack my changes.

**Comment by Parabak** [comment]
I think I've created the MR in the wrong way 😅 I can't see my changes in devel 🤷‍♂️ Moreover, there is only one green tick ⏫ 

@nicklockwood could you help me to manage it 😊

**Comment by nicklockwood** [comment]
@Parabak ah sorry, I moved your commits into another branch temporarily. I'll put them back into develop.

**Comment by Parabak** [comment]
😅 np, please ping me then. Could you please also release it is as _0.48.1_ ?

**Comment by Parabak** [comment]
@nicklockwood could you please tell me when we could expecti t? 

p.s. I'm bit confused with GitHub 😅 It says that it was merged and closed but I still can't see `--conditionswrap`...

**Comment by nicklockwood** [comment]
@Parabak there are still some changes I want to make, and some testing to do before I release this feature, so I'm not sure how long it will be, sorry.

It has been merged, but I've moved it to a local feature branch which is why it's not currently visible.

**Comment by Parabak** [comment]
Good day, sir 😊

Could you please give me news? Sorry for pushing it forward, I haven't rebased my forked one for a quite a long time, so I afraid to do it as well, but I really need a new version due to SwiftUI formatting 🙈

**Comment by nicklockwood** [comment]
@Parabak it was causing a lot of issues when I ran it on my regression suite, and I've not had a chance to investigate, sorry.

**Comment by Parabak** [comment]
Thanks for your reply. Do you have it in your agenda ? 😅 I think it’s nice
to have option…

**Comment by nicklockwood** [comment]
Sure. I'll try to rebase it on develop soon so at least you can use a more up-to-date version.

**Comment by Parabak** [comment]
🎗️ 
if you need help I can try to rebase it on my own, but I'm afraid it will take me way more time

**Comment by Parabak** [comment]
Hey @nicklockwood  👋 
Have you tried to rebase it recently? Are there many conflicts?

**Comment by Parabak** [comment]
Hey @nicklockwood, do you have this PR in your agenda?

**Pull request merged**
