### PR TITLE
Add dry mode

### PR DESCRIPTION
**Pull request by Johennes**
This adds a new commandline option `--dry` that when specified
prevents actual file changes and instead prints out a log message
for every file that would have been changed.

Relates to #155

### CODE REVIEW

**Comment by nicklockwood** [comment]
Sorry this didn't make it into the latest release, but I haven't forgotten about it - just thinking about the API.

**Comment by nicklockwood** [comment]
@Johennes would you mind rebasing the PR? Then I'll merge it.

**Comment by Johennes** [comment]
@nicklockwood I rebased on top of master. Let me know if anything else should be changed. If you merge this, you probably have to rebuild the binary under `CommandLineTool` because I couldn't do it with the current team setup in the project. Thanks for looking getting back on this. :)

**Comment by nicklockwood** [comment]
Thanks!

**Pull request merged**
